# Generated by Django 4.2.2 on 2023-06-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
