# Generated by Django 4.2.2 on 2023-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='login_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
