version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A conf worker -l INFO # Command used to start the Celery worker in the Docker container
    volumes:
      - .:/app
    env_file:
      - .env
      # depends on show that celery worker service requires the web service and the redis service to run
    depends_on: 
      - web
      - redis
  
  redis:
    image: redis:6-alpine