# Generated by Django 4.2.2 on 2023-07-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_enabled', models.CharField(blank=True, choices=[('GA', 'Google Authenticator'), ('Email', 'Email')], max_length=255, null=True)),
                ('otp_base32', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_auth_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
