# Generated by Django 4.2.2 on 2023-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logout_task_id',
            field=models.CharField(default='NA'),
        ),
    ]
