# Generated by Django 4.2.2 on 2023-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_iat',
            field=models.IntegerField(null=True),
        ),
    ]
