# Generated by Django 4.1.9 on 2023-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_auth_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_base32",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_enabled",
            field=models.CharField(
                blank=True,
                choices=[("GA", "Google Authenticator"), ("Email", "Email")],
                max_length=255,
                null=True,
            ),
        ),
    ]
