# Generated by Django 4.1.9 on 2023-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
