# Generated by Django 4.2.2 on 2023-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_otp_auth_url_user_otp_base32_user_otp_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_enabled',
            field=models.CharField(blank=True, choices=[('GA', 'Google Authenticator'), ('Email', 'Email')], null=True),
        ),
    ]
