# Generated by Django 4.2.2 on 2023-06-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_otp_auth_url_alter_user_otp_base32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
