# Generated by Django 4.1.9 on 2023-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_user_email_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_enabled",
            field=models.CharField(
                blank=True,
                choices=[("GA", "Google Authenticator"), ("Email", "Email")],
                max_length=255,
                null=True,
            ),
        ),
    ]
